apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka-demo
spec:
  spec:
  entityOperator:
    topicOperator:
      reconciliationIntervalSeconds: 90
    userOperator:
      reconciliationIntervalSeconds: 120
  kafka:
    version: 2.8.0
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    listeners:
       - name: external
         port: 9094
         tls: true
         type: route
         authentication:
          checkIssuer: true
          jwksEndpointUri: >-
            https://<keycloak:host>/auth/realms/demo/protocol/openid-connect/certs
          userNameClaim: preferred_username
          checkAccessTokenType: true
          accessTokenIsJwt: true
          enableOauthBearer: true
          validIssuerUri: >-
            https://<keycloak:host>/auth/realms/demo
          tlsTrustedCertificates:
            - certificate: keycloak.crt
              secretName: ca-keycloak
          type: oauth
    logging:
      loggers:
        log4j.logger.io.strimzi: DEBUG
      type: inline
    replicas: 1
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral